import os
import math
import sys
import types
import maya.cmds as cmds
import maya.OpenMaya as OpenMaya
import maya.OpenMayaAnim as OpenMayaAnim
import marigold.utility.NodeUtility as NodeUtility
import marigold.utility.TransformUtility as TransformUtility
import marigold.utility.XMLUtility as XMLUtility
import marigold.controllers.marigoldControls as marigoldControls
import marigold.skeleton.marigoldJoints as marigoldJoints
import marigold.meta.metaNode as metaNode
import marigold.utility.NurbsCurveUtility as NurbsCurveUtility
import marigold.components as Components
import marigold.utility.GeneralUtility as GeneralUtility


# @@@@@
'''
# making a matrix attr with cmd
cmds.addAttr( newObj, longName='testMatrix', dataType="matrix")
cmds.setAttr( '{0}.testMatrix'.format(newObj), (1,0,0,0,0,1,0,0,0,0,1,0,2,3,4,1), type='matrix' )
'''

'''
selList = cmds.ls( selection=True )
parent = selList[0]
print parent
children = cmds.listRelatives( parent, type='transform', allDescendents=True )
pShape = cmds.listRelatives( parent, type='shape', allDescendents=False )
print children
print pShape

shapes = cmds.listRelatives( pShape[0], type='shape', allDescendents=True )
print shapes
'''

'''
displayRGBColor -c userDefined1 0.904 0.889783 0.2712;
displayRGBColor -c userDefined2 0.607843 0.229029 0.182353;
displayRGBColor -c userDefined3 0.4095 0.63 0.189;
displayRGBColor -c userDefined4 0.189 0.63 0.3654;
displayRGBColor -c userDefined5 0.189 0.63 0.63;
displayRGBColor -c userDefined6 0.189 0.4051 0.63;
displayRGBColor -c userDefined7 0.43596 0.189 0.63;
displayRGBColor -c userDefined8 0.63 0.189 0.41391;
'''

        

def addMatrixAttr( targetObj, attrName ):
    mObj = NodeUtility.getDependNode( targetObj )
    dgModifier = OpenMaya.MDGModifier()

    mAttr = OpenMaya.MFnMatrixAttribute()
    controlMatrix = mAttr.create( attrName, attrName, OpenMaya.MFnMatrixAttribute.kDouble )
    dgModifier.addAttribute( mObj, controlMatrix )
    dgModifier.doIt()
        

#========================

AISEnvFacade
AlembicNode
ComputeGlobal
ComputeLocal
ControlBox
ControlBoxManip
CustomRigDefaultMappingNode
CustomRigRetargeterNode
HIKCharacterNode
HIKCharacterStateClient
HIKControlSetNode
HIKEffector2State
HIKEffectorFromCharacter
HIKFK2State
HIKPinning2State
HIKProperty2State
HIKRetargeterNode
HIKSK2State
HIKSkeletonGeneratorNode
HIKSolverNode
HIKState2Effector
HIKState2FK
HIKState2GlobalSK
HIKState2SK
addDoubleLinear
addMatrix
adskMaterial
adskPrepareRenderGlobals
aimConstraint
airField
airManip
alignCurve
alignManip
alignSurface
ambientLight
angleBetween
angleDimension
animBlend
animBlendInOut
animBlendNodeAdditive
animBlendNodeAdditiveDA
animBlendNodeAdditiveDL
animBlendNodeAdditiveF
animBlendNodeAdditiveFA
animBlendNodeAdditiveFL
animBlendNodeAdditiveI16
animBlendNodeAdditiveI32
animBlendNodeAdditiveRotation
animBlendNodeAdditiveScale
animBlendNodeBoolean
animBlendNodeEnum
animBlendNodeTime
animClip
animCurveTA
animCurveTL
animCurveTT
animCurveTU
animCurveUA
animCurveUL
animCurveUT
animCurveUU
animLayer
anisotropic
annotationShape
apfEntityNode
apfFileNode
arcLengthDimension
areaLight
arrayMapper
arrowManip
assemblyDefinition
assemblyReference
attachCurve
attachSurface
attrHierarchyTest
audio
avgCurves
avgCurvesManip
avgNurbsSurfacePoints
avgSurfacePoints
axesActionManip
ballProjManip
barnDoorManip
baseLattice
bevel
bevelManip
bevelPlus
bezierCurve
bezierCurveToNurbs
blendColorSets
blendColors
blendDevice
blendManip
blendShape
blendTwoAttr
blendWeighted
blindDataTemplate
blinn
boneLattice
boolean
boundary
brownian
brush
bulge
bump2d
bump3d
buttonManip
cMuscleCreator
cMuscleDebug
cMuscleDirection
cMuscleDisplace
cMuscleDisplay
cMuscleFalloff
cMuscleKeepOut
cMuscleMultiCollide
cMuscleObject
cMuscleRelative
cMuscleShader
cMuscleSmartCollide
cMuscleSmartConstraint
cMuscleSpline
cMuscleSplineDeformer
cMuscleStretch
cMuscleSurfAttach
cMuscleSystem
cacheBlend
cacheFile
camera
cameraManip
cameraPlaneManip
cameraSet
cameraView
centerManip
character
characterMap
characterOffset
checker
choice
chooser
circleManip
circleSweepManip
clamp
clipGhostShape
clipLibrary
clipScheduler
clipToGhostData
closeCurve
closeSurface
closestPointOnMesh
closestPointOnSurface
cloth
cloud
cluster
clusterFlexorShape
clusterHandle
coiManip
collisionModel
colorProfile
componentManip
composeMatrix
concentricProjManip
condition
container
containerBase
contrast
copyColorSet
copyUVSet
cpManip
crater
creaseSet
createBPManip
createCVManip
createColorSet
createEPManip
createUVSet
cubeManip
cubicProjManip
curveEdManip
curveFromMeshCoM
curveFromMeshEdge
curveFromSubdivEdge
curveFromSubdivFace
curveFromSurfaceBnd
curveFromSurfaceCoS
curveFromSurfaceIso
curveInfo
curveIntersect
curveNormalizerAngle
curveNormalizerLinear
curveSegmentManip
curveVarGroup
cylindricalProjManip
dagContainer
dagPose
dataBlockTest
decomposeMatrix
defaultLightList
defaultRenderUtilityList
defaultRenderingList
defaultShaderList
defaultTextureList
deformBend
deformBendManip
deformFlare
deformFlareManip
deformSine
deformSineManip
deformSquash
deformSquashManip
deformTwist
deformTwistManip
deformWave
deformWaveManip
deleteColorSet
deleteComponent
deleteUVSet
detachCurve
detachSurface
directedDisc
directionManip
directionalLight
discManip
diskCache
displacementShader
displayLayer
displayLayerManager
distanceBetween
distanceDimShape
distanceManip
dof
dofManip
doubleShadingSwitch
dpBirailSrf
dragField
dropoffLocator
dropoffManip
dynAttenuationManip
dynController
dynGlobals
dynHolder
dynSpreadManip
dynamicConstraint
editMetadata
emitterManip
enableManip
envBall
envChrome
envCube
envFacade
envFog
envSky
envSphere
environmentFog
eulerToQuat
explodeNurbsShell
expression
extendCurve
extendCurveDistanceManip
extendSurface
extendSurfaceDistanceManip
extrude
extrudeManip
facade
ffBlendSrf
ffBlendSrfObsolete
ffFilletSrf
ffd
fieldManip
fieldsManip
file
filletCurve
fitBspline
flexorShape
flow
fluidEmitter
fluidShape
fluidSliceManip
fluidTexture2D
fluidTexture3D
follicle
forceUpdateManip
fosterParent
fourByFourMatrix
fractal
frameCache
freePointManip
freePointTriadManip
gammaCorrect
geoConnectable
geoConnector
geometryConstraint
geometryFilter
geometryOnLineManip
geometryVarGroup
glBox
glCone
glCylinder
glSphere
glTorus
globalCacheControl
globalStitch
gpuCache
granite
gravityField
greasePencilSequence
greasePlane
greasePlaneRenderShape
grid
groupId
groupParts
guide
hairConstraint
hairSystem
hairTubeShader
hardenPoint
hardwareRenderGlobals
hardwareRenderingGlobals
heightField
hierarchyTestNode1
hierarchyTestNode2
hierarchyTestNode3
hikEffector
hikFKJoint
hikFloorContactMarker
hikGroundPlane
hikHandle
hikIKEffector
hikSolver
historySwitch
holdMatrix
hsvToRgb
hwReflectionMap
hwRenderGlobals
hyperGraphInfo
hyperLayout
hyperView
ik2Bsolver
ikEffector
ikHandle
ikMCsolver
ikPASolver
ikRPManip
ikRPsolver
ikSCsolver
ikSplineManip
ikSplineSolver
ikSpringSolver
ikSystem
imagePlane
implicitBox
implicitCone
implicitSphere
indexManip
insertKnotCurve
insertKnotSurface
instancer
intersectSurface
inverseMatrix
isoparmManip
jiggle
joint
jointCluster
jointClusterManip
jointFfd
jointLattice
jointTranslateManip
keyframeRegionManip
keyingGroup
lambert
lattice
layeredShader
layeredTexture
leastSquaresModifier
leather
lightFog
lightInfo
lightLinker
lightList
lightManip
limitManip
lineManip
lineModifier
locator
lodGroup
lodThresholds
loft
lookAt
luminance
makeGroup
makeIllustratorCurves
makeNurbCircle
makeNurbCone
makeNurbCube
makeNurbCylinder
makeNurbPlane
makeNurbSphere
makeNurbTorus
makeNurbsSquare
makeTextCurves
makeThreePointCircularArc
makeThreePointCircularArcManip
makeTwoPointCircularArc
makeTwoPointCircularArcManip
mandelbrot
mandelbrot3D
manip2DContainer
manipContainer
marble
markerManip
materialFacade
materialInfo
membrane
mentalrayTexture
mesh
meshVarGroup
motionPath
motionPathManip
motionTrail
motionTrailShape
mountain
moveBezierHandleManip
moveVertexManip
movie
mpBirailSrf
multDoubleLinear
multMatrix
multilisterLight
multiplyDivide
mute
nCloth
nComponent
nParticle
nRigid
nearestPointOnCurve
network
newtonField
newtonManip
nexManip
noise
nonLinear
normalConstraint
nucleus
nurbsCurve
nurbsCurveToBezier
nurbsSurface
nurbsTessellate
nurbsToSubdiv
nurbsToSubdivProc
objectAttrFilter
objectBinFilter
objectFilter
objectMultiFilter
objectNameFilter
objectRenderFilter
objectScriptFilter
objectSet
objectTypeFilter
ocean
oceanShader
offsetCos
offsetCosManip
offsetCurve
offsetCurveManip
offsetSurface
offsetSurfaceManip
oldBlindDataBase
oldGeometryConstraint
oldNormalConstraint
oldTangentConstraint
opticalFX
orientConstraint
orientationMarker
pairBlend
paramDimension
parentConstraint
particle
particleAgeMapper
particleCloud
particleColorMapper
particleIncandMapper
particleSamplerInfo
particleTranspMapper
partition
passContributionMap
passMatrix
pfxHair
pfxToon
phong
phongE
pivot2dManip
pivotAndOrientManip
place2dTexture
place3dTexture
planarProjManip
planarTrimSurface
plusMinusAverage
pointConstraint
pointEmitter
pointLight
pointMatrixMult
pointOnCurveInfo
pointOnCurveManip
pointOnLineManip
pointOnPolyConstraint
pointOnSurfManip
pointOnSurfaceInfo
pointOnSurfaceManip
poleVectorConstraint
polyAppend
polyAppendVertex
polyAutoProj
polyAutoProjManip
polyAverageVertex
polyBevel
polyBlindData
polyBoolOp
polyBridgeEdge
polyChipOff
polyCloseBorder
polyCollapseEdge
polyCollapseF
polyColorDel
polyColorMod
polyColorPerVertex
polyCone
polyConnectComponents
polyCopyUV
polyCrease
polyCreaseEdge
polyCreateFace
polyCreateToolManip
polyCube
polyCut
polyCutManip
polyCutManipContainer
polyCylProj
polyCylinder
polyDelEdge
polyDelFacet
polyDelVertex
polyDuplicateEdge
polyEdgeToCurve
polyEditEdgeFlow
polyExtrudeEdge
polyExtrudeFace
polyExtrudeManip
polyExtrudeManipContainer
polyExtrudeVertex
polyFlipEdge
polyFlipUV
polyHelix
polyHoleFace
polyLayoutUV
polyMapCut
polyMapDel
polyMapSew
polyMapSewMove
polyMappingManip
polyMergeEdge
polyMergeFace
polyMergeUV
polyMergeVert
polyMergeVertsManip
polyMirror
polyModifierManip
polyMoveEdge
polyMoveFace
polyMoveFacetUV
polyMoveUV
polyMoveUVManip
polyMoveVertex
polyMoveVertexManip
polyNormal
polyNormalPerVertex
polyNormalizeUV
polyOptUvs
polyPipe
polyPlanarProj
polyPlane
polyPlatonicSolid
polyPoke
polyPokeManip
polyPrimitiveMisc
polyPrism
polyProj
polyProjManip
polyProjectCurve
polyPyramid
polyQuad
polyReduce
polySelectEditFeedbackManip
polySeparate
polySewEdge
polySmooth
polySmoothFace
polySmoothProxy
polySoftEdge
polySphProj
polySphere
polySpinEdge
polySplit
polySplitEdge
polySplitRing
polySplitToolManip1
polySplitVert
polyStraightenUVBorder
polySubdEdge
polySubdFace
polyToSubdiv
polyToolFeedbackManip
polyTorus
polyTransfer
polyTriangulate
polyTweak
polyTweakUV
polyUVRectangle
polyUnite
polyVertexNormalManip
polyWedgeFace
positionMarker
postProcessList
precompExport
projectCurve
projectTangent
projectTangentManip
projection
projectionManip
projectionMultiManip
projectionUVManip
propModManip
propMoveTriadManip
proxyManager
psdFileTex
quadPtOnLineManip
quadShadingSwitch
quatAdd
quatConjugate
quatInvert
quatNegate
quatNormalize
quatProd
quatSub
quatToEuler
radialField
ramp
rampShader
rbfSrf
rbfSrfManip
rebuildCurve
rebuildSurface
record
reference
remapColor
remapHsv
remapValue
renderBox
renderCone
renderGlobals
renderGlobalsList
renderLayer
renderLayerManager
renderPass
renderPassSet
renderQuality
renderRect
renderSphere
renderTarget
renderedImageSource
resolution
resultCurveTimeToAngular
resultCurveTimeToLinear
resultCurveTimeToTime
resultCurveTimeToUnitless
reverse
reverseCurve
reverseCurveManip
reverseSurface
reverseSurfaceManip
revolve
revolveManip
revolvedPrimitiveManip
rgbToHsv
rigidBody
rigidConstraint
rigidSolver
rock
rotateHelper
rotateLimitsManip
rotateManip
rotateUV2dManip
roundConstantRadius
roundConstantRadiusManip
roundRadiusCrvManip
roundRadiusManip
sampler
samplerInfo
scaleConstraint
scaleLimitsManip
scaleManip
scaleUV2dManip
screenAlignedCircleManip
script
scriptManip
sculpt
selectionListOperator
sequenceManager
sequencer
setRange
shaderGlow
shadingEngine
shadingMap
shellTessellate
shot
simpleTestNode
simpleVolumeShader
singleShadingSwitch
sketchPlane
skinBinding
skinCluster
smoothCurve
smoothTangentSrf
snapshot
snapshotShape
snow
softMod
softModHandle
softModManip
solidFractal
spBirailSrf
sphericalProjManip
spotCylinderManip
spotLight
spotManip
spring
squareSrf
squareSrfManip
stencil
stereoRigCamera
stitchAsNurbsShell
stitchSrf
stitchSrfManip
stroke
strokeGlobals
stucco
styleCurve
subCurve
subSurface
subdAddTopology
subdAutoProj
subdBlindData
subdCleanTopology
subdHierBlind
subdLayoutUV
subdMapCut
subdMapSewMove
subdMappingManip
subdPlanarProj
subdProjManip
subdTweak
subdTweakUV
subdiv
subdivCollapse
subdivComponentId
subdivReverseFaces
subdivSurfaceVarGroup
subdivToNurbs
subdivToPoly
substance
substanceOutput
surfaceEdManip
surfaceInfo
surfaceLuminance
surfaceShader
surfaceVarGroup
symmetryConstraint
tangentConstraint
texLattice
texLatticeDeformManip
texMoveShellManip
texSmoothManip
texSmudgeUVManip
textButtonManip
textManip2D
texture3dManip
textureBakeSet
textureToGeom
time
timeFunction
timeToUnitConversion
timeWarp
toggleManip
toggleOnLineManip
toolDrawManip
toolDrawManip2D
toonLineAttributes
towPointOnCurveManip
towPointOnSurfaceManip
trans2dManip
transUV2dManip
transferAttributes
transform
transformGeometry
translateLimitsManip
translateManip
translateUVManip
transposeMatrix
trim
trimManip
trimWithBoundaries
triplanarProjManip
tripleShadingSwitch
trsInsertManip
trsManip
turbulenceField
turbulenceManip
tweak
uniformField
unitConversion
unitToTimeConversion
unknown
unknownDag
unknownTransform
untrim
useBackground
uv2dManip
uvChooser
vectorProduct
vectorRenderGlobals
vertexBakeSet
viewColorManager
volumeAxisField
volumeBindManip
volumeFog
volumeLight
volumeNoise
volumeShader
vortexField
water
weightGeometryFilter
wire
wood
wrap
writeToColorBuffer
writeToDepthBuffer
writeToLabelBuffer
writeToVectorBuffer
wtAddMatrix
xformManip


